/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package moocfihelsinki;

import moocfihelsinki.fitbyte.Fitbyte;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        var assistant = new Fitbyte(30, 60);
        double percentage = 0.5;

        while(percentage < 1.0){
            double target = assistant.targetHeartRate(percentage);
            System.out.println("Target " + (percentage * 100) + "% of maximum " + target);
            percentage = percentage + 0.1;
        }
    }
}
