/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package moocfihelsinki;

import main.java.moocfihelsinki.account.Account;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        var testAccount = new Account(100.00);
        System.out.println("Initial balance: " + testAccount.getBalance().toString());
        testAccount.deposit(20.00);
        System.err.println("After deposit balance:" + testAccount.getBalance().toString());
    }
}
